services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    container_name: trackit-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  trackit:
    image: martinden/trackit:latest
    environment:
      DB_HOST: "db"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "5432"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      SECRET_KEY: "${SECRET_KEY}"
      DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE}"
      PASSWORD_RESET_BASE_URL: "${PASSWORD_RESET_BASE_URL}"

    container_name: trackit_app
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        pytest -v --create-db
      "