# Generated by Django 5.2.3 on 2025-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="tasks",
                to="tasks.tags",
                verbose_name="Tags",
            ),
        ),
    ]
