# Generated by Django 5.2.3 on 2025-07-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_tasks_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="tasks.tags", verbose_name="Tags"
            ),
        ),
    ]
