# Generated by Django 5.2.3 on 2025-07-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_tasks_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="planned_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
