# Generated by Django 5.2.3 on 2025-07-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_passwordreset"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordReset",
        ),
    ]
