# Generated by Django 5.2.3 on 2025-07-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_delete_passwordreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskitem",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="taskitem",
            name="name",
            field=models.CharField(default="temp", max_length=256, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="taskitem",
            name="planned_date",
            field=models.DateField(blank=True, null=True, verbose_name="Planned date"),
        ),
        migrations.AddField(
            model_name="taskitem",
            name="status",
            field=models.CharField(
                choices=[("process", "In Process"), ("completed", "Completed")],
                default="process",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="templatetaskitem",
            name="name",
            field=models.CharField(default="temp", max_length=256, verbose_name="Name"),
        ),
    ]
