# Generated by Django 5.2.3 on 2025-07-13 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_taskitem_description_taskitem_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="templatetasks",
            name="tags",
        ),
        migrations.AddField(
            model_name="tags",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="taskitem",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="tasks.tags", verbose_name="Tags"
            ),
        ),
        migrations.AddField(
            model_name="templatetaskitem",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="templatetasks",
                to="tasks.tags",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
            preserve_default=False,
        ),
    ]
