# Generated by Django 5.2.3 on 2025-08-10 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_remove_tasks_tags_remove_templatetasks_tags_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tags",
            options={
                "ordering": ["name"],
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.AlterModelOptions(
            name="taskitem",
            options={"verbose_name": "Подзадача", "verbose_name_plural": "Подзадачи"},
        ),
        migrations.AlterModelOptions(
            name="tasks",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.AlterModelOptions(
            name="templatetasks",
            options={
                "verbose_name": "Шаблон задачи",
                "verbose_name_plural": "Шаблоны задач",
            },
        ),
        migrations.AlterField(
            model_name="tags",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Time_update"),
        ),
    ]
